# For batch mode

# Use multithreaded mode, 4 cores
/run/numberOfThreads 4

# Initialise kernel
/run/initialize

# Does this print progress bar?
# /run/printProgress 100000

# 100,000 events
# /run/beamOn 100000

# 10,000 events (100,000 is very time consuming with optical photons) (maybe even as low as 100 for testing)
# /run/beamOn 100  # (this is near instantaneous)
#/run/beamOn 1000  # this only takes ~10 seconds
# /run/beamOn 10000 # takes ~100 seconds (just short of 2 mins)
# NOTE: This was without reflection in place

# 10,000 events (100,000 is very time consuming with optical photons) (maybe even as low as 100 for testing)
# /run/beamOn 100  # (this is near instantaneous)
#/run/beamOn 1000  # this takes ~27 seconds
/run/beamOn 5000  # this takes ~135 seconds (scales mostly linearly)
# /run/beamOn 10000 # takes ~100 seconds (just short of 2 mins)
