# For batch mode

# Use multithreaded mode (3 cores, 3 threads)
/run/numberOfThreads 3

# Initialise kernel
/run/initialize

# Print progress every X events (Minimal impact on run time)
/run/printProgress 10000 # Print progress every 10% (every 10,000 events)

# 100,000 events (5000 takes ~135s with direct 662 keV gamma, but decay means much fewer interactions, 100,000 with isotropic source took ~3 mins)
# due to decay, and optical photons, sim time could fluctuate a lot for same amount of events
/run/beamOn 100000 # with decay, since less gammas interact with detector, need more events (256 bins) (~3 mins, ~7cm source-detector, 4 cores 4 threads)
# POST COMP REF: (~22m, 3cm source-detector, 3 cores 3 threads)
# POST VBOX REINSTALL: (~3m, ~7cm source-detector, 3 cores 3 threads), (~9m, 3cm source-detector, 3 cores 3 threads)
# NEXT DAY POST REBOOT: (~8m, ~7cm source-detector, 3 cores 3 threads)
# VBOX REINSTALL AGAIN: (~3m, ~7cm source-detector, 3 cores 3 threads)
# POST REBOOT: (~8m, ~7cm source-detector, 3 cores 3 threads)
# POST WSL INSTALL & REBOOT: (~8m, ~7cm source-detector, 3 cores 3 threads)
# POST WSL INSTALL & RESTART: (~3m, ~7cm source-detector, 3 cores 3 threads), (~9m, 3cm source-detector, 3 cores 3 threads), (~5m, ~7cm source-detector, 2 cores 2 threads)

# /run/beamOn 200000 # for 1024 bins (~6 mins)
# /run/beamOn 300000 # for 1024 bins (~X mins)
# /run/beamOn 400000 # for 1024 bins (~X mins)
