# For batch mode
# Call: ./gps run.mac

###################
# EXPERIMENT CONFIG
###################

# Set crystal diameter
#/experiment/detector/crystalSize 3 inch
/experiment/detector/crystalSize 2 inch
#/experiment/detector/crystalSize 1 inch

# Set source detector distance
/experiment/source/sourceDetectorDist 3 cm

# Set radioactive isotope
/experiment/source/isotope 137Cs
#/experiment/source/isotope 133Ba
#/experiment/source/isotope 60Co
#/experiment/source/isotope 22Na


#######
# Setup
#######

# Use multithreaded mode (3 cores, 3 threads)
/run/numberOfThreads 3 # NOTE: Using less threads results in slower simulations

# Initialise kernel
/run/initialize

# Print progress every X events (Minimal impact on run time)
/run/printProgress 10000 # Print progress every 10% (every 10,000 events) (for 100,000 total)


####################
# Radioactive Source
####################

# Set up the general particle source (137Cs) (defaults to 137Cs if source not specified)
# /gps/particle ion
# /gps/ion 55 137 0 0 # (Z, Atomic Mass, Charge, Excitation Energy)
# /gps/ion 55 137 # (Z, Atomic Mass, Charge, Excitation Energy)
#
# Specify volumetric source and spherical volume
#/gps/pos/type Volume
#/gps/pos/shape Sphere
# Specify the origin and radius of the sphere
#/gps/pos/centre 0. 0. 2.90425 cm
#/gps/pos/radius 1 mm
# Confine the volumetric source to the geometry with the name "Source"
#/gps/pos/confine Source

# TODO: REMOVE ALL OF THIS ^^


#############
# Output Data
#############

# Disable everything except per-event photon counts
# Disable all event data
/output/event/detection true
/output/event/detectionFraction false
/output/event/boundaryAbsorbFraction false
/output/event/bulkAbsorbFraction false

# Disable all detection data
/output/step/detection/coords false
/output/step/detection/distance false
/output/step/detection/timeOfFlight false
/output/step/detection/reflections false

# Disable all boundary absorption data
/output/step/boundaryAbsorb/coords false

# Disable all bulk absorption data
/output/step/bulkAbsorb/distance false
/output/step/bulkAbsorb/reflections false


###########
# Start Run
###########

# Run simulation for X events
# /run/beamOn 10000 # (~2m for 3' crystal)
# /run/beamOn 50000 # (~9m for 3' crystal)
#/run/beamOn 100000 # (~17m) (~21m) (~19m) (~18m) (~22m) (~27m w/ reflections & ntuple merging) (~24m w/ reflections & no ntuple merging) (~24m w/ reflections v2 & ntuple merging) (~22m w/ reflections v2 & ntuple merging & absorb process caching) (~18-19m for 3' crystal w/ all but spectra output disabled) (~17m no grease) (~10m for 2' crystal)
/run/beamOn 200000 # (~38m for 3' crystal) (~15m for 2' crystal) (~20m for 2' crystal)
#/run/beamOn 300000 # (~56m for 3' crystal) (~36m for 2' crystal)
# /run/beamOn 400000 # (~1hr 14m for 3' crystal)
# /run/beamOn 500000 # (~1hr 30m - ~1hr 40m for 3' crystal)
#/run/beamOn 800000 # (~19m for 1' crystal)
# /run/beamOn 1000000 # (~3hr 35m for 3' crystal)
#/run/beamOn 1200000 # 1.2m events (~?hr ?m for 3' crystal) (~2hr 6m for 2' crystal) (~?hr ?m for 1' crystal)

# NOTE: Due to decay and optical photons, sim time could fluctuate a lot for same amount of events (only if random seed is enabled, else result is repeatable)
