# For batch mode
# Call: ./gps run.mac

# Use multithreaded mode (3 cores, 3 threads)
/run/numberOfThreads 3

# Initialise kernel
/run/initialize

# Print progress every X events (Minimal impact on run time)
/run/printProgress 10000 # Print progress every 10% (every 10,000 events) (for 100,000 total)

# Set up the general particle source (241Am) (defaults to 137Cs if source not specified)
/gps/particle ion
/gps/ion 95 241 0 0 # (Z, Atomic Mass, Charge, Excitation Energy)
# /gps/ion 95 241 # (Z, Atomic Mass, Charge, Excitation Energy)
#
# Specify volumetric source and spherical volume
/gps/pos/type Volume
/gps/pos/shape Sphere
# Specify the origin and radius of the sphere
/gps/pos/centre 0. 0. 2.90425 cm
/gps/pos/radius 1 mm
# Confine the volumetric source to the geometry with the name "Source"
#/gps/pos/confine Source

# In this case, limit the time threshold to below 237Np T1/2 of 2.144*10^6 (2,144,000) years (will override the val in main)
# with default 1*10^60 we see full Neptunium decay chain, which is not very realistic given 237Np long lifetime
# 233Pa T1/2 only 27d, 233U 159,200y
# /process/had/rdm/thresholdForVeryLongDecayTime 1.0e+7 year # include 237Np, but not its daughters
/process/had/rdm/thresholdForVeryLongDecayTime 1.0e+4 year # Just 241Am (433y T1/2)

# Run for X events (1024 bins)
# due to decay, and optical photons, sim time could fluctuate a lot for same amount of events
# /run/beamOn 10000 # (~?m)
# /run/beamOn 50000 # (~?m)
/run/beamOn 100000 # (~8m, just 241Am)
# /run/beamOn 200000 # (~?m)
# /run/beamOn 300000 # (~?m)
# /run/beamOn 400000 # (~?m)
