#
# This file permits to customize, with commands,
# the menu bar of the G4UIXm, G4UIQt, G4UIWin32 sessions.
# It has no effect with G4UIterminal.
#
# Process vis.mac (and draw geometry)
#
# /control/execute vis.mac # NOTE: This line is redundant given prior call in main(), will just spawn another window
#
# File menu:
/gui/addMenu file File
/gui/addButton file Quit exit
#
# Run menu:
/gui/addMenu run Run
/gui/addButton run "beamOn 1" "/run/beamOn 1"
#
# Source Menu:
/gui/addMenu source Source
/gui/addButton source "137Cs" "/gps/ion 55 137 0 0"
/gui/addButton source "60Co" "/gps/ion 27 60 0 0"
/gui/addButton source "22Na" "/gps/ion 11 22 0 0"
/gui/addButton source "241Am" "/gps/ion 95 241 0 0"
/gui/addButton source "68Ge" "/gps/ion 32 68 0 0"
