#
# This file permits to customize, with commands,
# the menu bar of the G4UIXm, G4UIQt, G4UIWin32 sessions.
# It has no effect with G4UIterminal.
#
# Process vis.mac (and draw geometry)
#
# /control/execute vis.mac # NOTE: This line is redundant given prior call in main(), will just spawn another window
#
# File menu:
/gui/addMenu file File
/gui/addButton file Quit exit
#
# Run menu:
/gui/addMenu run Run
/gui/addButton run "beamOn 1" "/run/beamOn 1"
#
# Source Menu:
/gui/addMenu source Source
/gui/addButton source "137Cs" "/gps/ion 55 137 0 0"
/gui/addButton source "60Co" "/gps/ion 27 60 0 0"
/gui/addButton source "22Na" "/gps/ion 11 22 0 0"
/gui/addButton source "241Am" "/gps/ion 95 241 0 0"
/gui/addButton source "68Ge" "/gps/ion 32 68 0 0"


#### TODO: Either add gps source setup code here (from test.mac), or call an external "place_source.mac", which is the same as test.mac, minus the run/beamOn call

#### TODO: Add a way to alter the source-detector distance

#### This should be like a pseudo lab experience, choose source, place it X distance from detector face, run either 1 event, or potentially run batch mode
##   ^ if adding batch mode menu buttons, will want to disable trajectories drawing, etc

#### TODO: Add a way to change detector geometry (i.e. switch between 3', 2', and 1' NaI:Tl detector)
##   ^^ as well as changing detector material (i.e., NaI:Tl, LaBr:Ce, CeBr) (code optical params in c++ then switch selection via messenger)
##   ^^ maybe expose api via messenger for changing things like reflector material too
