# For batch mode
# Call: ./gps run.mac

# Use multithreaded mode (3 cores, 3 threads)
/run/numberOfThreads 3

# Initialise kernel
/run/initialize

# Print progress every X events (Minimal impact on run time)
/run/printProgress 10000 # Print progress every 10% (every 10,000 events) (for 100,000 total)

# Set up the general particle source (60Co)
# NOTE: Defaults to 137Cs if source not specified (may want a seperate run macro for a few sources)
# /gps/particle ion
# /gps/ion 55 137 0 0 # (Z, Atomic Mass, Charge, Excitation Energy)
# /gps/ion 55 137 # (Z, Atomic Mass, Charge, Excitation Energy)
#
# Specify volumetric source and spherical volume
/gps/pos/type Volume
/gps/pos/shape Sphere
# Specify the origin and radius of the sphere
/gps/pos/centre 0. 0. 2.90425 cm
/gps/pos/radius 1 mm
# Confine the volumetric source to the geometry with the name "Source"
#/gps/pos/confine Source

# Run 100,000 events (decay means fewer interactions in the detector, compared to monoenergetic particle gun, so number of events must be high, for 1024 bins)
# due to decay, and optical photons, sim time could fluctuate a lot for same amount of events
#
# /run/beamOn 10000 # (3cm, 3 cores 3 threads) (~2m, 137Cs)
# /run/beamOn 50000 # (3cm, 3 cores 3 threads) (~9m, 137Cs) (~28m 60Co)
#
/run/beamOn 100000 # (~17m 137Cs) (~59m 60Co)
# POST COMP REF -- EM4: (~28m just now - 4 cores 4 threads) (~1hr 2m - 2 cores 4 threads) (~52m - 2 cores 2 threads), EM1: (~54m 2-2), EM4: (~39m 3 cores 3 threads) (~35m 3 cores 3 threads)
# POST VBOX REINSTALL: (~15m, 3cm source-detector, 3 cores 3 threads)
# POST REBOOT: (~35m, 3cm source-detector, 3 cores 3 threads)
# POST WSL INSTALL: (~18m, 3cm source-detector, 3 cores 3 threads)
# PIXE Enabled: (~18-20m, 3cm source-detector, 3 cores 3 threads)
# PRIMARY GENERATOR FIXED: (~17m, 3cm source-detector, 3 cores 3 threads)
#
# /run/beamOn 200000 # (~38m)
# /run/beamOn 300000 # (~56m)
# /run/beamOn 400000 # (<2hr 24m, probably much less but didnt check in between)

