# For batch mode
# Call: ./gps run.mac

###################
# EXPERIMENT CONFIG
###################

# Crystal diameter
#/experiment/detector/crystalSize 3 inch
/experiment/detector/crystalSize 2 inch
#/experiment/detector/crystalSize 1 inch

# Reflector thickness (axial & radial)
/experiment/detector/reflectorAxialThickness 0.23495 cm # 0.23495 cm default
/experiment/detector/reflectorRadialThickness 0.23495 cm # 0.23495 cm default

# Enclosure thickness (axial & radial)
/experiment/detector/enclosureAxialThickness 0.0508 cm # 0.0508 cm default
/experiment/detector/enclosureRadialThickness 0.0508 cm # 0.0508 cm default

# Enclosure material (axial & radial)
/experiment/detector/enclosureAxialMaterial Aluminium # Aluminium default
/experiment/detector/enclosureRadialMaterial Aluminium # Aluminium default

# Source-detector-distance
/experiment/source/sourceDetectorDist 3 cm

# Radioactive isotope
/experiment/source/isotope 137Cs
#/experiment/source/isotope 133Ba
#/experiment/source/isotope 60Co
#/experiment/source/isotope 22Na

# Source retainer window material/thickness
/experiment/source/sourceWindowMaterial Mylar # Mylar default
/experiment/source/sourceWindowThickness 0.0125 cm # 0.0125 cm default

#######
# Setup
#######

# Use multithreaded mode (3 cores, 3 threads)
/run/numberOfThreads 3 # NOTE: Using less threads results in slower simulations
#/run/numberOfThreads 8 # NOTE: Using less threads results in slower simulations

# Initialise kernel
/run/initialize

# Print progress every X events (Minimal impact on run time)
/run/printProgress 10000 # Print progress every 10% (every 10,000 events) (for 100,000 total)

#############
# Output Data
#############

# Disable everything except per-event photon counts
# Disable all event data
/output/event/detection true
/output/event/detectionFraction false
/output/event/boundaryAbsorbFraction false
/output/event/bulkAbsorbFraction false

# Disable all detection data
/output/step/detection/coords false
/output/step/detection/distance false
/output/step/detection/timeOfFlight false
/output/step/detection/reflections false

# Disable all boundary absorption data
/output/step/boundaryAbsorb/coords false

# Disable all bulk absorption data
/output/step/bulkAbsorb/distance false
/output/step/bulkAbsorb/reflections false

###########
# Start Run
###########

# Run simulation for X events
# /run/beamOn 10000 # (~2m for 3' crystal)
# /run/beamOn 50000 # (~9m for 3' crystal)
#/run/beamOn 100000 # (~17m) (~21m) (~19m) (~18m) (~22m) (~27m w/ reflections & ntuple merging) (~24m w/ reflections & no ntuple merging) (~24m w/ reflections v2 & ntuple merging) (~22m w/ reflections v2 & ntuple merging & absorb process caching) (~18-19m for 3' crystal w/ all but spectra output disabled) (~17m no grease) (~10m for 2' crystal)
/run/beamOn 200000 # (~38m for 3' crystal) (~15m for 2' crystal) (~20m for 2' crystal)
#/run/beamOn 300000 # (~56m for 3' crystal) (~36m for 2' crystal)
# /run/beamOn 400000 # (~1hr 14m for 3' crystal)
# /run/beamOn 500000 # (~1hr 30m - ~1hr 40m for 3' crystal)
#/run/beamOn 800000 # (~19m for 1' crystal)
# /run/beamOn 1000000 # (~3hr 35m for 3' crystal)
#/run/beamOn 1200000 # 1.2m events (~?hr ?m for 3' crystal) (~2hr 6m for 2' crystal) (~?hr ?m for 1' crystal)

# NOTE: Due to decay and optical photons, sim time could fluctuate a lot for same amount of events (only if random seed is enabled, else result is repeatable)
