# Top-down Visualisation Macro

###################
# EXPERIMENT CONFIG
###################

/experiment/detector/crystalSize 2 inch
#/experiment/source/sourceDetectorDist 3 cm

######
# INIT
######

# Initialise Geant4 framework
/run/initialize

# Check for overlaps (the overlap warning doesnt abort sim, and the normal warning is lost in stdout)
/geometry/test/run

##########
# GRAPHICS
##########

# Initialise graphical output (qt window) OpenGL - 600 window
#/vis/open OGL 600x600-0+0
#/vis/open OGLIQt 600x600-0+0 # OpenGLImmediateQt
#/vis/open OGLI 600x600-0+0 # OpenGLImmediateQt

#/vis/open OGL 600x600-0+0
#/vis/open OGL 600x600-0+0
#/vis/open OGL 600x600-0+0
#/vis/open OGL 600x600-0+0

# OpenGLStoredX
#/vis/open OGLSX 600x600-0+0

# TOOLSSG_X11_ZB (NOPE)
#/vis/open TSG_X11_ZB 600x600-0+0
#/vis/open TSGX11ZB 600x600-0+0

# TOOLSSG_QT_GLES (Seems to fix z-fighting)
# /vis/open TSG_QT_GLES 600x600-0+0
# /vis/open TSGQt 600x600-0+0
/vis/open TSG 600x600-0+0  ## SEEMS TO BE THE BEST FOR THIS TOP-DOWN VIEW ??

# TOOLSSG_QT_ZB
#/vis/open TSG_QT_ZB 600x600-0+0 # Seems to fix z-fighting  (but still not clean)
#/vis/open TSGQtZB 600x600-0+0 # Seems to fix z-fighting  (but still not clean)

# RayTracer
# /vis/open RayTracer 600x600-0+0
# /vis/open RayTracerX 600x600-0+0 # Need to add to cmake to use


# ASCIITree ATree DAWNFILE G4HepRepFile HepRepFile RayTracer VRML2FILE gMocrenFile TOOLSSG_OFFSCREEN TSG_OFFSCREEN TSG_FILE 
# OpenGLImmediateQt OGLIQt OGLI OpenGLStoredQt OGLSQt OGL OGLS OpenGLImmediateX OGLIX OpenGLStoredX OGLSX TOOLSSG_X11_GLES 
# TSG_X11_GLES TSGX11 TOOLSSG_X11_ZB TSG_X11_ZB TSGX11ZB TOOLSSG_QT_GLES TSG_QT_GLES TSGQt TSG TOOLSSG_QT_ZB TSG_QT_ZB TSGQtZB

# Registered graphics systems are:
# ASCIITree (ATree)
# DAWNFILE (DAWNFILE)
# G4HepRepFile (HepRepFile)
# RayTracer (RayTracer)
# VRML2FILE (VRML2FILE)
# gMocrenFile (gMocrenFile)
# TOOLSSG_OFFSCREEN (TSG_OFFSCREEN, TSG_FILE)
# OpenGLImmediateQt (OGLIQt, OGLI)
# OpenGLStoredQt (OGLSQt, OGL, OGLS)
# OpenGLImmediateX (OGLIX, OGLIQt_FALLBACK)
# OpenGLStoredX (OGLSX, OGLSQt_FALLBACK)
# TOOLSSG_X11_GLES (TSG_X11_GLES, TSGX11, TSG_QT_GLES_FALLBACK)
# TOOLSSG_X11_ZB (TSG_X11_ZB, TSGX11ZB)
# TOOLSSG_QT_GLES (TSG_QT_GLES, TSGQt, TSG)
# TOOLSSG_QT_ZB (TSG_QT_ZB, TSGQtZB)

# Disable auto refresh whilst scene is established:
/vis/viewer/set/autoRefresh false

#######
# SCENE
#######

# Draw the volumes (will be empty otherwise)
/vis/drawVolume

# Display a scale for the scene
#/vis/scene/add/scale 10 cm
# NOTE: Without adding scale zoom messes up randomly

# Display coordinate system
#/vis/scene/add/axes
#/vis/scene/add/axes 0 0 0 5 cm # at xyz(0,0,0), 5cm long axis line

# Hide volumes
/vis/geometry/set/visibility World 0 false
/vis/geometry/set/visibility Table 0 false
/vis/geometry/set/visibility SourceActive 0 false
/vis/geometry/set/visibility SourceRetainer 0 false
/vis/geometry/set/visibility SourceRetainerWindow 0 false
/vis/geometry/set/visibility SourceCasing 0 false
/vis/geometry/set/visibility SourceCasingWindow 0 false
/vis/geometry/set/visibility SourceHolder 0 false

# Set colours (args: volume, depth, red, green, blue, opacity)
/vis/geometry/set/colour Scintillator 0 1. 1. 1. 1. # white
/vis/geometry/set/colour ReflectorRadial 0 0. 0. 1. 1. # blue
/vis/geometry/set/colour ReflectorAxial 0 0. 0. 1. 1. # blue
/vis/geometry/set/colour OpticalGrease 0 1. 1. 0. 1. # yellow
/vis/geometry/set/colour OpticalWindow 0 0. 1. 1. 1. # teal
/vis/geometry/set/colour Photocathode 0 1. 0. 0. 1. # red
#/vis/geometry/set/colour EnclosureRadial 0 0.8 0.8 0.8 1. # mid-light gray
#/vis/geometry/set/colour EnclosureAxial 0 0.8 0.8 0.8 1. # mid-light gray
#/vis/geometry/set/colour HermeticSeal 0 0.8 0.8 0.8 1. # mid-light gray
/vis/geometry/set/colour EnclosureRadial 0 0.7 0.7 0.7 1. # mid-light gray
/vis/geometry/set/colour EnclosureAxial 0 0.7 0.7 0.7 1. # mid-light gray
/vis/geometry/set/colour HermeticSeal 0 0.7 0.7 0.7 1. # mid-light gray

# ...
/vis/geometry/set/forceSolid all

######
# VIEW
######

/vis/viewer/set/background 1. 1. 1.

# Section cut (half-cut)
/vis/viewer/addCutawayPlane 0 5 0 cm 0 -1 0 # along y-axis

# Specify style (surface or wireframe):
/vis/viewer/set/style surface
#/vis/viewer/set/style wireframe

# Set cut aways to add or multiply
#/vis/viewer/set/cutawayMode union # add (default value)
#/vis/viewer/set/cutawayMode intersection # multiply

# ...
#/vis/viewer/set/hiddenEdge true
/vis/viewer/set/hiddenEdge false

# ...
/vis/viewer/set/auxiliaryEdge true
#/vis/viewer/set/auxiliaryEdge false

# Increase cylindrical tesselation to reduce staggered gradient on enclosure
#/vis/viewer/set/lineSegmentsPerCircle 100
#/vis/viewer/set/lineSegmentsPerCircle 300
/vis/viewer/set/lineSegmentsPerCircle 360

########
# CAMERA
########

# ....
/vis/viewer/set/projection orthogonal
# NOTE: Reduces z-fighting seemingly

# Centre camera on detector origin
/vis/viewer/centreOn Scintillator

# Top down view
# /vis/viewer/set/upVector 0 0 10
# /vis/viewer/set/viewpointThetaPhi 270. 270.
#
# Set the positive Z axis as the cameras Y axis
/vis/viewer/set/upVector 0 0 1
# ...
/vis/viewer/set/viewpointVector 0 1 0
# NOTE: This achieves the same view

# Zoom in on detector origin
#/vis/viewer/zoom 12
#/vis/viewer/zoom 6
/vis/viewer/zoom 1.5

# Update viewer with the changes
/vis/viewer/refresh

# If changes are made, viewer will automatically be updated
/vis/viewer/set/autoRefresh true

####
#
####

#/vis/open RayTracer
#/vis/viewer/copyViewFrom viewer-0
#/vis/viewer/set/all viewer-0
#/vis/rayTracer/trace
#/vis/viewer/refresh
#/vis/viewer/refresh viewer-1
