###################
# EXPERIMENT CONFIG
###################

/experiment/detector/crystalSize 3 inch
#/experiment/detector/crystalSize 1 inch

#/experiment/source/sourceDetectorDist 10 cm
/experiment/source/sourceDetectorDist 3 cm

# /experiment/source/isotope 137Cs # TODO


######
# INIT
######

# Initialise Geant4 framework
/run/initialize

# Initialise graphical output (qt window) OpenGL - 600 window
/vis/open OGL 600x600-0+0

# If changes are made, viewer will automatically be updated
/vis/viewer/set/autoRefresh true

# Draw the volumes (will be empty otherwise)
/vis/drawVolume

# Show particle trajectories at end of event, 2 pixels wide (wont be shown by default)
/vis/scene/add/trajectories smooth

# Allow more than one particle to be seen in the viewer (accumulates sequentially)
/vis/scene/endOfEventAction accumulate

# Display a scale for the scene
/vis/scene/add/scale 10 cm

# Display coordinate system
# /vis/scene/add/axes

# Display the ID of each event
/vis/scene/add/eventID

# To disambiguate between gamma and other uncharged particles (neutrino/anti-neutrino), select colour by particle ID:
/vis/modeling/trajectories/create/drawByParticleID
# ... and add step points 
#/vis/modeling/trajectories/drawByParticleID-0/default/setDrawStepPts true
#
# To draw only gammas:
#/vis/filtering/trajectories/create/particleFilter
#/vis/filtering/trajectories/particleFilter-0/add gamma
#
# To invert the above, drawing all particles except gammas,
# keep the above two lines but also add:
#/vis/filtering/trajectories/particleFilter-0/invert true

# Radioactive decay module verbose level (3 max)
# /process/had/rdm/verbose 3

# Snap to axis
#
# Face View 1
# /vis/viewer/set/viewpointThetaPhi 0. 0.
#
# Side View 1
# /vis/viewer/set/viewpointThetaPhi 90. 0.
#
# Face View 2
# /vis/viewer/set/viewpointThetaPhi 180. 0.
#
# Side View 2
# /vis/viewer/set/viewpointThetaPhi 270. 0.

# Bottom up view
# /vis/viewer/set/upVector 0 0 1
# /vis/viewer/set/viewpointThetaPhi 270. 90.
#
# Top down view
# /vis/viewer/set/upVector 0 0 1
# /vis/viewer/set/viewpointThetaPhi 270. 270.

# Check for overlaps (the overlap warning doesnt abort sim, and the normal warning is lost in stdout)
/geometry/test/run

###########
# COLOURING
###########

# Set colours (args: volume, depth, red, green, blue, opacity)
/vis/geometry/set/colour World 0 0. 0. 1. 0.1 // blue (transparent)
/vis/geometry/set/colour Table 0 0.95 0.95 0.95 1. // light gray

/vis/geometry/set/colour Scintillator 0 1. 1. 1. 0.5 // white (part-transparent)
/vis/geometry/set/colour Reflector 0 0. 0. 1.0 0.5 // blue
/vis/geometry/set/colour Enclosure 0 0.8 0.8 0.8 1. // mid-light gray (solid)
/vis/geometry/set/colour OpticalGrease 0 1.0 1.0 0. 0.75 // yellow
/vis/geometry/set/colour OpticalWindow 0 0.8 0.8 0.8 0.25 // mid-light gray (transparent)
/vis/geometry/set/colour Photocathode 0 1. 0. 0. 0.5 // red
/vis/geometry/set/colour HermeticSeal 0 0.9 0.9 0.9 1. // light gray (opaque)

/vis/geometry/set/colour SourceActive 0 0.0 1.0 0.0 1. // green
/vis/geometry/set/colour SourceRetainer 0 0.8 0.8 0.8 1. // mid-light gray (solid)
/vis/geometry/set/colour SourceRetainerWindow 0 0.8 0.8 0.8 0.25 // mid-light gray (transparent)
/vis/geometry/set/colour SourceCasing 0 0.8 0.8 0.8 1. // mid-light gray (opaque)
/vis/geometry/set/colour SourceCasingWindow 0 0.8 0.8 0.8 0.25 // mid-light gray (transparent)
/vis/geometry/set/colour SourceHolder 0 0.1 0.1 0.1 1. // charcoal (opaque)

/vis/geometry/set/forceSolid all

########
# CAMERA
########

# ...
/vis/geometry/set/visibility World 0 false

# Set the viewer to designated viewpoint
/vis/viewer/set/viewpointVector 1 1 1 # look at (1, 1, 1)

# ...
# /vis/viewer/zoom 6
/vis/viewer/zoom 7

#  ...
/vis/viewer/centreOn Scintillator

# ...
/vis/viewer/set/viewpointVector -180 90 90
