# For batch mode
# Call: ./gps run.mac

# Use multithreaded mode, 4 cores
/run/numberOfThreads 4

# Initialise kernel
/run/initialize

# Does this print progress bar?
# /run/printProgress 100000

# Set up the general particle source
#
# Specify volumetric source and spherical volume
/gps/pos/type Volume
/gps/pos/shape Sphere
# Specify the origin and radius of the sphere
/gps/pos/centre 0. 0. 2.90425 cm
/gps/pos/radius 1 mm
# Confine the volumetric source to the geometry with the name "Source"
#/gps/pos/confine Source

# NOTE: Defaults to 137Cs, but may want a seperate run macro for a few sources

# 100,000 events (5000 takes ~135s with direct 662 keV gamma, but decay means much fewer interactions, 100,000 with isotropic source took ~3 mins)
# due to decay, and optical photons, sim time could fluctuate a lot for same amount of events
/run/beamOn 100000 # with decay, since less gammas interact with detector, need more events (256 bins) (~3 mins)    (~7m now ...)
# /run/beamOn 200000 # for 1024 bins (~6 mins)
# /run/beamOn 300000 # for 1024 bins (~ mins)
# /run/beamOn 400000 # for 1024 bins (~25 mins)
