# Macro file for example B1
#
# Can be run in batch, without graphic
# or interactively: Idle> /control/execute run1.mac
#
# Change the default number of workers (in multi-threading mode)
#/run/numberOfThreads 4
#
# Initialize kernel
/run/initialize
#
/control/verbose 2
/run/verbose 2
/event/verbose 0
/tracking/verbose 1
#
# gamma 6 MeV to the direction (0.,0.,1.)
#
#/gun/particle gamma
#/gun/energy 0.662 MeV
#
# gamma 662 keV isotropic
#
/gps/particle gamma
#/gps/energy 0.662 MeV
/gps/ene/mono 0.662 MeV
# Isotropic should be default, but must be setting to direction somewhere in code (as all still goes to 0,0,1)
/gps/ang/type iso
#
# /run/beamOn 5
/run/beamOn 10
